### ISSUE TITLE
generated grpc node client does not work

### ISSUE THREAD

**Issue by jmuk** [googleapis/packman#35]
Generated Node.JS gRPC client does not load.
```
> require('./index')
Error: extended message protobuf.MethodOptions is not defined
    at Error (native)
    at ProtoBuf.Builder.BuilderPrototype.create (/ssd/mukai/gapi/gapi-dev/packman/pubsub/nodejs/node_modules/protobufjs/dist/ProtoBuf.js:4523:35)
    at ProtoBuf.Builder.BuilderPrototype.import (/ssd/mukai/gapi/gapi-dev/packman/pubsub/nodejs/node_modules/protobufjs/dist/ProtoBuf.js:4669:22)
    at Object.<anonymous> (/ssd/mukai/gapi/gapi-dev/packman/pubsub/nodejs/service.js:1:126)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Even after tweaking the order of include manually, it actually does not return a valid gRPC client in it.
Generated one (such as LoggingServiceV2 or Publisher) creates an instance of RpcImpl, which is in protobufjs. Not the ones in grpc.

**Comment by jmuk** [comment]
@tbetbetbe is off these days, I'll work on this on behalf.

**Comment by jmuk** [comment]
correction: not rpcImpl but ProtoBuf.Reflect.Service instance.

Anyways, I suspect that the pbjs-generated json/commonjs files are not friendly to grpc -- that's not what grpc expects. The easier way is to bundle the .proto files directly.
